globalThis.runOneTabImportBundle = function runOneTabImportBundle() {
// Copyright 2026 OneTab Ltd.  All rights reserved.
const {
  version: pn,
  false1: Jo,
  false2: Qo,
  false3: Ko,
  false4: Xo,
  false5: Vo,
  false6: _o,
  true1: Yo,
  chromeUrl: ta,
  chromeNewTabUrl: ea,
  websiteUrl: De,
  false7: ia,
  false8: sa,
  true2: na,
  false9: ra,
  oneTabPageUrl: xn,
  extensionRootUrl: de,
  tabGroupsEnabled: Wi,
  hasTabGroupsPermission: oa,
  requestTabGroupsPermission: aa,
  requestPermission: Ci,
  isOneTabPageUrl: zi,
  isExtensionUrl: la,
  stripHttpProtocol: wn,
  domainWithoutWww: Zi,
  extractDomain: Ee,
  protocolPrefix: ha,
  commonDomainSuffixes: Ji,
  registeredDomain: mn,
  addNoCacheRandom: yn,
  noCacheRandom: bn,
  postJson: ua,
  fetchJson: gn,
  randomAlphabet: ti,
  randomId: kn,
  randomHex: ca,
  newId: Bt,
  textEncoder: Tn,
  textDecoder: fa,
  digestBytes: An,
  digestText: $n,
  stableIdFromText: ei,
  trimWhitespace: ii,
  isLineBreak: In,
  nonStandardLineBreaks: vn,
  normalizeLineBreaks: On,
  removeControlCharacters: Qi,
  removeControlCharactersExceptTabs: Ki,
  normalizedOrDefault: si,
  normalizeText: Wt,
  endsWith: Mn,
  compareVersionParts: Xi,
  versionLessThan: Ln,
  versionGreaterThan: Gn,
  versionBetween: da,
  defaultSettings: pa,
  moveElementToIndex: Sn,
  insertBeforeElement: Pn,
  div: f,
  createElement: F,
  internalProps: Fn,
  createNode: pe,
  readerUrlPrefix: Vi,
  normalizeUrl: At,
  placeholderUrlFor: Dn,
  isFileAccessBlocked: xa,
  parseDigits: wa,
  last: ma,
  backoffSteps: _i,
  backoffDurations: En,
  waitForCondition: ya,
  translate: w,
  runWhenDomReady: ba,
  horizontalDivider: xe,
  relativeTimeFormatter: Bn,
  relativeTimeUnits: Yi,
  relativeTime: ts,
  relativePastTime: es,
  relativeFutureTime: Hn,
  deepEqual: Be,
  sortObjectDeep: is,
  clearArray: ss,
  uniqueBy: jn,
  arrayInsert: qn,
  sameSet: Un,
  sameJson: ga,
  pushUnique: ee,
  includes: Ht,
  includesAny: Xt,
  removeAll: ni,
  removeWhere: ka,
  toggleValue: Ta,
  removeFirstWhere: Aa,
  maybeArray: O,
  removeOccurrence: $a,
  mapIdsToItems: Ia,
  filterToSet: va,
  filterNested: Rn,
  not: He,
  partition: ri,
  partitionMany: Oa,
  asyncPartition: Ma,
  activateTab: La,
  activateTabAndWindow: Ga,
  randomItem: Sa,
  randomColor: Pa,
  excludedUrlPrefixes: Nn,
  isExcludedUrl: ns,
  saveUncommittedChanges: ie,
  clearUncommittedChanges: Fa,
  getUncommittedChanges: rs,
  clearAllUncommittedChanges: Da,
  pruneUncommittedChanges: Wn,
  localStorageAdapter: zn,
  getLocalStorageAdapter: Ea,
  placeholderParts: Ra,
  makeProxyHandler: Za,
  identity: hi,
  intersperseLocal: Xa,
  childTypeCode: Va,
  editTypeCode: _a,
  tabTypeCode: Ya,
  sessionStorageAdapter: er,
  getSessionStorageAdapter: tl,
  runtimeMarker: ir,
  renderLabelSegments: ls,
  tabCount: di,
  bookmarkCount: ar,
  replaceLabelSegments: pi,
  htmlEscapeText: mt,
  htmlEscapeAttribute: cs,
  identityPair: Ne,
  EventAttachment: fs,
  itemOccurrenceRef: gt,
  AsyncMapCache: dr,
  hasNotesText: ol,
  nonNegative: ds,
  isTabExcluded: al,
  isPlaceholderUrl: pr,
  shouldSkipTab: ll,
  allSame: hl,
  escapeXml: ul,
  isChromium120OrNewer: xr,
  colorNames: ps,
  defaultColor: me,
  true3: cl,
  leadingNonAlphanumeric: fl,
  measureElement: dl,
  modelPredicates: { isUndefined: ja, isDefined: Zn, hasId: Ua, doesNotHaveId: Jn, sameIdAs: qa, getId: Vt, isTab: j, isRoot: V, isTrash: yt, isFolder: G, isUserFolder: Na, isFolderOrWindowGroup: Ca, isGroup: _, isTabGroup: ct, isWindowGroup: $t, isBrowserGroup: zt, isSharedAndNotExpired: Qn },
  collectionHelpers: { compareDescendingBy: _t, mapBy: Kn, compareLocaleNumericBy: Wa, mergeOwnProperty: za, groupBy: Qa, range: Xn, nthIndexOf: Ka },
  searchHelpers: { splitSearchText: _n, splitSearchTextWithTerm: Yn },
  runtimeHelpers: { delay: Zt, replaceValueDeep: ui, isOpera: sr, isBrave: el, isMicrosoftEdge: nr, unsleepTab: il, mergeObjectsWithSeparators: ci, intersperse: sl, callIfOwnProperty: fi, callIfDefined: rr, joinUniqueTrimmed: nl },
  domTransitionHelpers: { fadeOut: or, fadeIn: rl },
  applyRuntimeHelpers: { applyValue: Ue, applyIfTruthy: vt },
  urlHelpers: { trimTrailingDotOrComma: lr, substringAfter: hr, stripProtocol: jt, equalIgnoringProtocol: Re, safeNormalizeText: Yt, canonicalizeTextAsUrl: hs, areUrlLikeEqual: us, isYouTubeUrl: ur, shouldUseCandidateUrl: cr, safeNonJavascriptUrl: se },
  textHelpers: { normalizeImportedText: fr },
  importHelpers: { parseImportedTabGroups: xi }
} = globalThis.createOneTabBundlePrelude({
  getCoreProxy: () => A,
  isNewOrBlankTabPageUrl: url => globalThis.isNewOrBlankTabPageUrl(url),
  pluralize: (key, count) => Ft(key, count),
  trimToLengthWithEllipsis: (...args) => Ks(...args),
});
const {
  taskFieldNames: ye,
  shareFieldNames: xs,
  sharedPageUrlPattern: pl,
  splitOversized: xl,
  isJson: wr,
  localeId: wi,
  helpUrl: wl,
  localizedPathPrefix: mr,
  matchesOrUnset: ws,
  getDirection: yr,
  isLtr: K,
  applyDocumentDirection: br,
  pluralize: Ft,
  groupPathLabel: ml,
  groupLabelParts: gr,
  groupDisplayLabel: be,
  groupFallbackLabel: mi,
  groupLabel: yi,
  debounceByType: kr,
  shouldApplyChrome145Workaround: Tr,
  isChrome145: Ar,
  uncollapseChrome145TabGroup: yl,
} = globalThis.createOneTabPageCommon({
  websiteUrl: De,
  translate: w,
  tabCount: di,
  isRoot: V,
  isTrash: yt,
  isFolder: G,
  isMicrosoftEdge: nr,
});
const { cleanUrlForSearch: $r } = globalThis.createOneTabUrlQueryCleanup();
const { ItemCache: kt } = globalThis.createOneTabItemCache(
  {
    get kt() { return kt; },
    get rt() { return rt; },
    get ge() { return ge; },
    get Ir() { return Ir; },
    get prettyPrintUrl() { return prettyPrintUrl; },
    get vr() { return vr; },
    get Or() { return Or; },
    get He() { return He; },
    get Ct() { return Ct; },
    get at() { return at; },
    get Vt() { return Vt; },
    get Mr() { return Mr; },
    get G() { return G; },
    get _() { return _; },
    get _t() { return _t; },
    get j() { return j; },
    get V() { return V; },
    get w() { return w; },
    get as() { return as; },
    get $r() { return $r; },
    get we() { return we; },
    get Gr() { return Gr; },
    get Zn() { return Zn; },
    get je() { return je; },
    get O() { return O; },
  }
);
const { S, bl, ge, rt, Ir, vr, Or, Mr, Lr, gl, Gr } = globalThis.createOneTabItemStore({
  hi,
  jn,
  Yt,
  cr,
  At,
  Ne,
  Bt,
  dr,
  get at() { return at; },
  get bt() { return bt; },
  Kn,
  Vt,
  _,
  G,
});
const { il: kl, Di: ne, le: gi, ur: Sr, cr: Pr, fi: ke, he: ki, cs: gs, $t: Mt, el: Tl, ue: Ti, ce: Ai, xs: $s, fr: Fr, dr: Dr, ws: Is, ms: vs, Kt: re } = globalThis.createOneTabBaseControls({ h: (...a) => f(...a), G: (...a) => F(...a), vi: (...a) => pe(...a), W: (...a) => C(...a), z: (...a) => J(...a), St: (...a) => Dt(...a), Ei: (...a) => Ze(...a), mi: (...a) => Oe(...a), bi: (...a) => Me(...a), O: (...a) => O(...a), Si: (...a) => Ue(...a), J: () => K(), Cs: (...a) => en(...a), Ni: (...a) => Xe(...a), Yt: (...a) => ae(...a), Qt: (...a) => ee(...a), Ji: (...a) => ii(...a), He: (...a) => Ki(...a), Be: (...a) => Qi(...a), se: (...a) => pi(...a), dn: (...a) => In(...a), spinner: (...a) => Mi(...a), getFt: () => Ut, getDnd: () => dnd, getP: () => D, getVt: () => { try { return Lt; } catch { return; } }, getFe: () => Ii, getLt: () => dt, getTooltip: () => ut, getQs: () => Vs });
const { bs: Os, pr: $i, Gi: We, kt: Ot, Pt: qt, ys: Ms, Xt: oe, W: C, yr: qr } = globalThis.createOneTabViewControls({
  get $r() { return Cr; },
  get $t() { return Mt; },
  get A() { return A; },
  get Ae() { return Ei; },
  get B() { return j; },
  get Bi() { return Je; },
  get Bn() { return Qn; },
  get Dt() { return Ht; },
  get Ei() { return Ze; },
  get Es() { return Zs; },
  get Fn() { return Jn; },
  get Fr() { return _r; },
  get Ft() { return Ut; },
  get G() { return F; },
  get Ii() { return Be; },
  get ItemCache() { return kt; },
  get J() { return K; },
  get Ki() { return oi; },
  get Kt() { return re; },
  get L() { return G; },
  get Ls() { return Rs; },
  get Mr() { return Zr; },
  get Mt() { return Ft; },
  get Ni() { return Xe; },
  get Nt() { return zt; },
  get O() { return O; },
  get Oe() { return qi; },
  get On() { return Un; },
  get P() { return D; },
  get Pe() { return zi; },
  get Ps() { return Cs; },
  get Qe() { return rs; },
  get Qn() { return rr; },
  get Qt() { return ee; },
  get St() { return Dt; },
  get Ts() { return Fs; },
  get We() { return es; },
  get X() { return Y; },
  get Yt() { return ae; },
  get Zn() { return or; },
  get Zt() { return ie; },
  get _() { return V; },
  get as() { return ws; },
  get bi() { return Me; },
  get bt() { return It; },
  get ci() { return be; },
  get cs() { return gs; },
  get displayAutoActionOnOpenOptionModal() { return displayAutoActionOnOpenOptionModal; },
  get dnd() { return dnd; },
  get dt() { return _; },
  get ee() { return di; },
  get et() { return ot; },
  get fi() { return ke; },
  get ft() { return xt; },
  get ge() { return Fi; },
  get getActiveTabInCurrentWindow() { return getActiveTabInCurrentWindow; },
  get getItemById() { return rt; },
  get getTabById() { return getTabById; },
  get gr() { return Ur; },
  get gt() { return vt; },
  get h() { return f; },
  get he() { return ki; },
  get hi() { return me; },
  get ie() { return fi; },
  get ji() { return Ke; },
  get lt() { return dt; },
  get mi() { return Oe; },
  get ms() { return vs; },
  get mt() { return $t; },
  get navigateToItem() { return navigateToItem; },
  get nt() { return ut; },
  get oi() { return xe; },
  get oneTabPage() { return oneTabPage; },
  get os() { return xs; },
  get ot() { return ct; },
  get qt() { return Zt; },
  get re() { return mi; },
  get showSharingModal() { return showSharingModal; },
  get ss() { return fs; },
  get st() { return ht; },
  get to() { return To; },
  get ue() { return Ti; },
  get ui() { return ye; },
  get ut() { return at; },
  get vn() { return Hn; },
  get we() { return Li; },
  get ws() { return Is; },
  get wt() { return bt; },
  get x() { return w; },
  get xi() { return Ie; },
  get xs() { return $s; },
  get xt() { return gt; },
  get ye() { return Pi; },
  get z() { return J; },
  get ze() { return ss; },
});
let ve, Ut;
const { gr: Ur, nl: $l, kr: Rr, rl: Il, Tr: Nr, lt: dt, Ar: Wr, ol: vl, $r: Cr, fe: Ii, vr: Ls, Ir: Gs, Or: zr, Mr: Zr, Sr: Jr, al: Ol } = createOneTabUiControls({ h: (...a) => f(...a), G: (...a) => F(...a), W: (...a) => C(...a), Xt: oe, O: (...a) => O(...a), ws: Is, co: (...a) => Do(...a), xe: (...a) => Mi(...a), z: (...a) => J(...a), ti: (...a) => le(...a), Kr: (...a) => yo(...a), x: (...a) => w(...a), Gs: (...a) => Ws(...a), J: () => K(), Yr: (...a) => ko(...a), Bs: (...a) => Js(...a), Ve: (...a) => ls(...a), Qt: (...a) => ee(...a), Zi: (...a) => ni(...a), ze: (...a) => ss(...a), oi: (...a) => xe(...a), St: (...a) => Dt(...a), getSettings: () => A, getModal: () => It, getTheme: () => ve, getTooltip: () => ut });
const {
  X: Y,
  st: ht,
  gs: Ss,
  de: vi,
  Lr: Qr,
  di: Te,
  Dr: Kr,
  Gr: Xr,
  ll: Ml,
  Se: Ri,
  ft: xt,
  Rt: Jt,
} = globalThis.createOneTabTreeRenderer({
  get $t() { return Mt; },
  get A() { return A; },
  get Ae() { return Ei; },
  get B() { return j; },
  get Ct() { return Xt; },
  get Dt() { return Ht; },
  get Ei() { return Ze; },
  get En() { return Ct; },
  get Fe() { return Zi; },
  get Ft() { return Ut; },
  get G() { return F; },
  get Hs() { return 300; },
  get Ht() { return Bt; },
  get Ii() { return Be; },
  get ItemCache() { return kt; },
  get J() { return K; },
  get Kt() { return re; },
  get L() { return G; },
  get Mt() { return Ft; },
  get Ni() { return Xe; },
  get Nt() { return zt; },
  get O() { return O; },
  get Oe() { return qi; },
  get Oi() { return we; },
  get P() { return D; },
  get Pr() { return (...a) => Vr(...a); },
  get Ps() { return (...a) => Cs(...a); },
  get Qe() { return rs; },
  get Qi() { return si; },
  get Si() { return Ue; },
  get Tn() { return Dn; },
  get W() { return C; },
  get We() { return es; },
  get Zr() { return wo; },
  get Zt() { return ie; },
  get _e() { return je; },
  get _s() { return ln; },
  get ai() { return _t; },
  get be() { return Si; },
  get bi() { return Me; },
  get bs() { return Os; },
  get bt() { return It; },
  get cr() { return Pr; },
  get dnd() { return dnd; },
  get dt() { return _; },
  get ee() { return di; },
  get fe() { return Ii; },
  get ge() { return Fi; },
  get getItemById() { return rt; },
  get gn() { return Pn; },
  get gt() { return vt; },
  get h() { return f; },
  get he() { return ki; },
  get hi() { return me; },
  get js() { return (...a) => Ks(...a); },
  get jt() { return Wt; },
  get ks() { return (...a) => Ps(...a); },
  get lt() { return dt; },
  get mi() { return Oe; },
  get ms() { return vs; },
  get nn() { return wn; },
  get ns() { return ds; },
  get oneTabPage() { return oneTabPage; },
  get or() { return gr; },
  get ot() { return ct; },
  get prettyPrintUrl() { return prettyPrintUrl; },
  get se() { return pi; },
  get te() { return ci; },
  get ue() { return Ti; },
  get ui() { return ye; },
  get ut() { return at; },
  get we() { return Li; },
  get wt() { return bt; },
  get x() { return w; },
  get xt() { return gt; },
  get ye() { return Pi; },
  get yn() { return Sn; },
  get yt() { return At; },
  get z() { return J; },
  get zi() { return ei; },
  get zt() { return Qt; },
});
const {
  pi: Ae,
  Pr: Vr,
  ks: Ps,
  Fr: _r,
  Ts: Fs,
  Pi: Ce,
  pe: Oi,
  As: Ds,
  $s: Es,
  hl: Yr,
  Er: to,
  ul: eo,
  vs: Bs,
  Br: io,
  cl: Ll,
  Fi: ze,
  Hr: so,
  jr: no,
  A,
  Vt: $e,
  Nr: ro,
  xi: Ie,
  Yt: ae,
  Ei: Ze,
  Bi: Je,
  fl: Gl,
  Is: Hs,
  qr: oo,
  Rr: ao,
  Hi: Qe,
  Os: js,
  Ms: qs,
  Ur: lo,
  Ss: Us,
  Ls: Rs,
  Ds: Ns,
  Wr: ho,
  xe: Mi,
  we: Li,
  Gs: Ws,
  Cr: uo,
  dl: Sl,
  Ps: Cs,
  pl: Pl,
  zr: co,
  Jr: fo,
  xl: Fl,
  me: Gi,
  Qr: po,
  Fs: zs,
  wl: Dl,
  ml: xo,
  Zr: wo,
  Es: Zs,
  ti: le,
  z: J,
  mi: Oe,
  _r: mo,
  bi: Me,
  ji: Ke,
  Bs: Js,
  Kr: yo,
  Hs: Qs,
  js: Ks,
  bl: El,
  yl: Bl,
  Xr: bo,
  Vr: go,
  gl: Hl,
  be: Si,
  kl: jl,
  Yr: ko,
  to: To,
  Tl: ql,
  Al: Ul,
  et: ot,
} = globalThis.createOneTabTreeActions({
  get $i() { return Ee; },
  get Ai() { return De; },
  get B() { return j; },
  get Cn() { return ir; },
  get Di() { return ne; },
  get Fe() { return Zi; },
  get G() { return F; },
  get Hn() { return Xn; },
  get Ht() { return Bt; },
  get ItemCache() { return kt; },
  get J() { return K; },
  get L() { return G; },
  get Ns() { return Xs; },
  get O() { return O; },
  get Se() { return Ri; },
  get Si() { return Ue; },
  get Sn() { return He; },
  get Sr() { return Jr; },
  get W() { return C; },
  get Xe() { return hi; },
  get Yi() { return ui; },
  get Ze() { return Vt; },
  get _() { return V; },
  get _i() { return ri; },
  get _n() { return ar; },
  get ci() { return be; },
  get cs() { return gs; },
  get dt() { return _; },
  get en() { return pn; },
  get getItemById() { return rt; },
  get getItems() { return ge; },
  get h() { return f; },
  get hi() { return me; },
  get lt() { return dt; },
  get mt() { return $t; },
  get navigateToItem() { return navigateToItem; },
  get oneTabPage() { return oneTabPage; },
  get ot() { return ct; },
  get qt() { return Zt; },
  get rr() { return br; },
  get ss() { return fs; },
  get te() { return ci; },
  get ut() { return at; },
  get x() { return w; },
  get xt() { return gt; },
  get yt() { return At; },
  get zi() { return ei; },
  get zt() { return Qt; },
  setThemeState({ wi: i, Ft: t }) { ve = i; Ut = t; },
});
let D = {};
const { vt: Lt, ye: Pi, Ni: Xe, ge: Fi, Ns: Xs, qi: Ve, io: Ao, qs: Vs, $l: Rl, eo: $o, Rs: _s, vl: Nl, ke: Di, so: Io, no: vo, Il: Wl, Te: Le, ro: Oo, Us: Ys, Ae: Ei, at: ft, Ws: tn, Cs: en, Ol: Mo, Ml: sn, zs: nn, Js: rn, $e: Bi, Sl: Cl, oo: Lo, Qs: on, ve: Hi, Ie: ji, Zs: an, _s: ln, Oe: qi } = globalThis.createOneTabTreeInteractions({get _(){return V},get _e(){return je},get _t(){return se},get A(){return A},get Ai(){return De},get ao(){return Go},get B(){return j},get Bi(){return Je},get ce(){return Ai},get Cr(){return uo},get Ct(){return Xt},get displayAutoActionOnOpenOptionModal(){return displayAutoActionOnOpenOptionModal},get dnd(){return dnd},get dt(){return _},get Dt(){return Ht},get er(){return wr},get es(){return cs},get et(){return ot},get fi(){return ke},get ft(){return xt},get G(){return F},get getItemById(){return rt},get getItems(){return ge},get Gi(){return We},get go(){return No},get gt(){return vt},get Gt(){return jt},get h(){return f},get he(){return ki},get hi(){return me},get ho(){return Po},get Ht(){return Bt},get iconGrid(){return iconGrid},get is(){return xi},get ItemCache(){return kt},get J(){return K},get ji(){return Ke},get Ki(){return oi},get Ks(){return hn},get kt(){return Ot},get L(){return G},get Ls(){return Rs},get lt(){return dt},get mt(){return $t},get Mt(){return Ft},get navigateToItem(){return navigateToItem},get Nr(){return ro},get ns(){return ds},get Nt(){return zt},get O(){return O},get oi(){return xe},get oneTabPage(){return oneTabPage},get ot(){return ct},get P(){return D},set P(value){D = value},get pi(){return Ae},get pt(){return mt},get Pt(){return qt},get qr(){return oo},get qt(){return Zt},get rn(){return mn},get Rr(){return ao},get rs(){return ps},get Rt(){return Jt},get showSharingModal(){return showSharingModal},get Ss(){return Us},get te(){return ci},get ti(){return le},get ut(){return at},get Vt(){return $e},get W(){return C},get x(){return w},get X(){return Y},get xi(){return Ie},get xs(){return $s},get xt(){return gt},get ys(){return Ms},get Yt(){return ae},get zt(){return Qt}});
let ut, Se;
const { Ks: hn, ao: Go, lo: So, Ll: zl, yi: Ge, Dl: Zl, zt: Qt, Gl: Jl, Xs: un, ho: Po, uo: Fo, bt: It, co: Do, fo: Eo, po: Bo, xo: Ho, Me: Ui, wo: jo, Vs: cn, mo: qo, bo: Uo, yo: Ro, go: No, Ys: fn, tn: dn, St: Dt, ko: Wo } = globalThis.createOneTabImportExportControls({get _(){return V},get _r(){return mo},get $s(){return Es},get A(){return A},get ai(){return _t},get As(){return Ds},get at(){return ft},get B(){return j},get bi(){return Me},get ci(){return be},get Cs(){return en},get Di(){return ne},get dt(){return _},get es(){return cs},get G(){return F},get Ge(){return Ci},get gi(){return Se},set gi(value){Se=value},get h(){return f},get He(){return Ki},get In(){return qn},get ir(){return xr},get Ir(){return Gs},get is(){return xi},get ItemCache(){return kt},get J(){return K},get jt(){return Wt},get Ke(){return os},get L(){return G},get lt(){return dt},get mi(){return Oe},get Mt(){return Ft},get nt(){return ut},set nt(value){ut=value},get O(){return O},get oe(){return yi},get Oi(){return we},get pt(){return mt},get ti(){return le},get vr(){return Ls},get Vt(){return $e},get W(){return C},get Ws(){return tn},get x(){return w},get yr(){return qr},get yt(){return At},get z(){return J}});
setTimeout(async () => {
  (await co(), await Yr(), await Co());
}, 1);
async function Co() {
  await zo();
}
async function zo() {
  document.body.style.backgroundColor = "var(--col-bg-color)";
  let i = new Ls({ style: { width: "720px", height: "400px", margin: "0 0" } }),
    t = pe(document.getElementById("contentAreaDiv"), void 0, {
      style: { padding: "0", maxWidth: "700px" },
      children: {
        header: Mo(
          w("importAndExport"),
          f({
            style: {
              flex: "1 0 auto",
              textAlign: "end",
              fontSize: "12px",
              marginInlineEnd: "30px",
              display: "flex",
            },
            children: [xo()],
          }),
        ),
        body: f({
          style: {
            marginTop: "103px",
            marginBottom: "60px",
            paddingInlineStart: "45px",
          },
          children: {
            Xx: sn(
              !0,
              w("importUrls"),
              f({
                style: {},
                children: {
                  Vx: Gs({
                    style: {
                      paddingInline: "0px 20px",
                      paddingBlock: "18px 10px",
                    },
                  }),
                  ox: i,
                  Qx: f({
                    style: { display: "flex", marginTop: "10px" },
                    children: {
                      Kx: new $i({
                        vr: w("chooseALocationToImportTo"),
                        Li: "destination",
                        style: {
                          marginInlineStart: "3px",
                          marginInlineEnd: "8px",
                        },
                        Eh: await rt("root"),
                        Z: document,
                        maxHeight: "500px",
                      }),
                      _x: new ne({
                        label: w("import"),
                        V: !0,
                        tabIndex: void 0,
                        fontSize: "12px",
                        $: {
                          flex: "0 0 auto",
                          marginInlineStart: "auto",
                          marginInlineEnd: "0px",
                        },
                        onclick: async () => {
                          let e = i.i.contentWindow.document.body.innerHTML;
                          if (!/\S/.test(e)) Qt(w("noTextHasBeenEntered"));
                          else {
                            let s = await xi(e),
                              n = t.u.Kx.ds,
                              r = n.id,
                              o = await A.Ma({ Ga: s, Gs: n.groupType, O: r });
                            (await A.ec({
                              itemId: n.id,
                              ...(o !== r && { Zi: o }),
                            }),
                              setTimeout(() => window.close(), 100));
                          }
                        },
                      }),
                    },
                  }),
                  Yx: f({
                    style: {
                      fontSize: "12px",
                      paddingTop: "20px",
                      paddingBottom: "20px",
                      paddingInlineStart: "4px",
                    },
                    textContent: w("toImportBrowserBookmarksUseMenuOption"),
                  }),
                },
              }),
            ),
            t0: eo(16),
            e0: sn(
              !0,
              w("exportUrls"),
              f({
                children: {
                  Fc: f({
                    style: { paddingBottom: "10px" },
                    textContent: w("exportThenImportNote"),
                  }),
                  Jx: F("textArea", {
                    style: {
                      width: "700px",
                      maxWidth: "800px",
                      height: "500px",
                      fontFamily: "monospace",
                      fontSize: "13px",
                      backgroundColor: "transparent",
                      "unicode-bidi": "plaintext",
                    },
                  }),
                  Qx: f({
                    style: { display: "flex", flexWrap: "wrap" },
                    children: {
                      source: f({
                        style: {
                          marginInlineStart: "5px",
                          marginTop: "20px",
                          marginInlineEnd: "auto",
                          flex: "1 1 auto",
                        },
                        children: {
                          i0: new $i({
                            vr: w("chooseExportLocation"),
                            Li: "source",
                            label: w("sourceColon"),
                            style: {
                              marginInlineStart: "3px",
                              marginInlineEnd: "8px",
                            },
                            Eh: await rt("root"),
                            Js: async (e) =>
                              (t.u.Jx.i.value = (
                                await Le({ groupId: e.id, ge: "urlAndTitle" })
                              ).Xe),
                            Z: document,
                            maxHeight: "500px",
                          }),
                        },
                      }),
                      buttons: f({
                        style: {
                          flex: "0 0 auto",
                          marginInlineStart: "auto",
                          display: "flex",
                          marginTop: "10px",
                          gap: "6px",
                          justifyContent: "flex-end",
                        },
                        children: {
                          s0: new ne({
                            label: w("copyToClipboard"),
                            V: !0,
                            tabIndex: void 0,
                            fontSize: "12px",
                            $: { flex: "0 0 auto", marginInlineEnd: "0px" },
                            onclick: async () => {
                              await navigator.clipboard.writeText(
                                t.u.Jx.i.value,
                              );
                            },
                          }),
                        },
                      }),
                    },
                  }),
                },
              }),
            ),
          },
        }),
      },
    });
  (i.jd(),
    (t.u.Jx.i.value = (await Le({ groupId: "root", ge: "urlAndTitle" })).Xe));
}
function Ql(i, t, e) {
  const s = document.createElement("a"),
    n = new Blob([i], { type: t }),
    r = URL.createObjectURL(n);
  (s.setAttribute("href", r), s.setAttribute("download", e), s.click());
}

};
